### ISSUE TITLE
Fails with Systemd

### ISSUE THREAD

**Issue by MTRNord** [Drakulix/simplelog.rs#4]
I have a very basic systemd service with this logger in it:

```
[Unit]
Description=Rust Imap Server
After=network-online.target

[Service]
ExecStart=/home/marcel/rust/IMAPServer-rs/target/debug/IMAPServer
User=root
Group=root

Environment=RUST_BACKTRACE=1

Restart=on-failure
SyslogIdentifier=IMAPServer

[Install]
WantedBy=multi-user.target
```

It fails with:

```
Jun 29 08:34:17 riot.nordgedanken.de IMAPServer[9675]:    0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:    1: std::sys_common::backtrace::_print
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/sys_common/backtrace.rs:71
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:    2: std::panicking::default_hook::{{closure}}
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/sys_common/backtrace.rs:60
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/panicking.rs:355
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:    3: std::panicking::default_hook
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/panicking.rs:371
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:    4: std::panicking::rust_panic_with_hook
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/panicking.rs:549
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:    5: std::panicking::begin_panic
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/panicking.rs:511
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:    6: std::panicking::begin_panic_fmt
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/panicking.rs:495
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:    7: rust_begin_unwind
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/panicking.rs:471
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:    8: core::panicking::panic_fmt
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libcore/panicking.rs:69
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:    9: core::panicking::panic
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libcore/panicking.rs:49
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:   10: <core::option::Option<T>>::unwrap
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libcore/macros.rs:21
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:   11: IMAPServer::helper::init_log
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./home/marcel/rust/IMAPServer-rs/src/helper.rs:13
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:   12: IMAPServer::main
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./home/marcel/rust/IMAPServer-rs/src/main.rs:36
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:   13: std::panicking::try::do_call
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/panicking.rs:454
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:   14: __rust_maybe_catch_panic
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libpanic_unwind/lib.rs:98
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:   15: std::rt::lang_start
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/panicking.rs:433
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/panic.rs:361
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:              at ./checkout/src/libstd/rt.rs:57
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:   16: main
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:   17: __libc_start_main
Jun 29 08:34:18 riot.nordgedanken.de IMAPServer[9675]:   18: _start
```

The code that fails is:

```rust
pub fn init_log() {
    let mut config_dir = get_config_dir();
    config_dir.push("IMAP.log");
    CombinedLogger::init(vec![TermLogger::new(LogLevelFilter::Info, simplelog::Config::default()).unwrap(),
                          WriteLogger::new(LogLevelFilter::Debug, simplelog::Config::default(), File::create(config_dir.to_str().unwrap())
                          .unwrap())])
    .unwrap();
}
```

The failing code is the CombinedLogger line

**Comment by MTRNord** [comment]
PS this line comes before the trace:

`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:323`

**Comment by Drakulix** [comment]
Yes. Don't unwrap the `TermLogger` it simply does not work on systemd, because systemd does not open a compatible stdout/err pipe. The `SimpleLogger` works, so usually I just use `TermLogger::new(...).or_else(|| SimpleLogger::new(...)).unwrap()`.

**Comment by MTRNord** [comment]
Ah ok I will try that and if it works close the issue. Thanks

**Comment by MTRNord** [comment]
@Drakulix using your suggested way ( ``TermLogger::new(LogLevelFilter::Info, simplelog::Config::default()).or_else(|| SimpleLogger::new(LogLevelFilter::Info, simplelog::Config::default())).unwrap()`` ) I get:

```
   Compiling IMAPServer v0.0.0 (file:///home/marcel/rust/IMAPServer-rs)
error[E0308]: mismatched types
  --> src/helper.rs:13:110
   |
13 |     CombinedLogger::init(vec![TermLogger::new(LogLevelFilter::Info, simplelog::Config::default()).or_else(|| SimpleLogger::new(LogLevelFilter::Info, simplelog::Config::default())).unwrap(),
   |                                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found struct `std::boxed::Box`
   |
   = note: expected type `std::option::Option<std::boxed::Box<simplelog::TermLogger>>`
              found type `std::boxed::Box<simplelog::SimpleLogger>`

error: aborting due to previous error

error: Could not compile `IMAPServer`.

```

**Comment by Drakulix** [comment]
Oh right, that was an `Option`, not a `Result`. I just did write that line down out of my head, but you should be able to get this working in a similar fashion.

For reference, my code is even more complex and looks like this:
```
    let verbosity = match CONFIG.log.verbosity {
        0 => LogLevelFilter::Error,
        1 => LogLevelFilter::Warn,
        2 => LogLevelFilter::Info,
        3 => LogLevelFilter::Debug,
        4 | _ => LogLevelFilter::Trace,
    };

    let mut logger: Vec<Box<SharedLogger>> = vec![];
    if !CONFIG.log.quiet {
        logger.push(match TermLogger::new(verbosity) {
            Some(termlogger) => termlogger,
            None => SimpleLogger::new(verbosity),
        });
    }
    match CONFIG.log.logfile {
        Some(ref path) => logger.push(FileLogger::new(cmp::max(verbosity, LogLevelFilter::Info), File::create(path).expect("Could not create logfile"))),
        None => {},
    }
    CombinedLogger::init(logger).expect("Could not initialize logger");
```

Where CONFIG is something provided by another module, but I am sure you get the idea.

**Comment by MTRNord** [comment]
Thanks that works
